export const SIGNUP_ACTION = '[actions] signup';
export const SET_USER_TOKEN_DATA_MUTATION = '[mutations] set user token';
export const LOADING_SPINNER_SHOW_MUTATION = '[mutations] show loader';
export const LOGIN_ACTION = '[actions] login user';
export const GET_USER_TOKEN_GETTER = '[getters] auth user token'
export const IS_AUTHENTICATE_GETTER = '[getters] is user authenticated'
export const LOGOUT_ACTION = '[actions] Logout user'
export const AUTH_ACTION = '[actions] Do user auth'
export const AUTO_ACTION_LOGIN = '[actions] Auth Auto Login'